sonar.projectKey = jenkins-pipeline
sonar.host = http://localhost:9000
sonar.sources = src/main, src/test
sonar.language=java
sonar.java.binaries=target/classes
sonar.login=sqp_4d806e429b6ce4119e368e7fdc84ade96d5510e1